### PR TITLE
#116 [Mod] add: option to complete propal line desc

### PR DESCRIPTION
**Pull request by FHenry**

### CODE REVIEW

**Comment by evarisk-micka** [comment]
Corriger les typos avant de merge

**Comment by FHenry** [comment]
> Corriger les typos avant de merge

@evarisk-micka : C'est à dire ? je ne me souviens plus de ce que nous avions dit

**Comment by FHenry** [comment]
@nicolas-eoxia 
I've seen that you partially use this PR to add feature but there is a missing setup config module part.
What's missing (after the merge conflict resolve I've just done) to merge this pr ?

**Comment by evarisk-micka** [comment]
@FHenry @nicolas-eoxia this branch has already been fixed and merged
5580029a4c34d08f58f7186d6ec2f17e310e452b

**Pull request closed without merging**
